### ISSUE TITLE
Buildings sharing nodes

### ISSUE THREAD

**Issue by RAytoun** [osmlab/applepaintstyles#13]
There is no visual evidence that buildings share nodes with each other until I click on the node. Then a red triangle appears. The red triangle should be there to begin with so that I have a visual indicator telling me to check if that is correct or not.
![Apple paint 1](https://user-images.githubusercontent.com/10500102/96309670-aee02600-0ffd-11eb-8bb4-7e9c270ec06e.jpg)

**Comment by westlakej** [comment]
Hey @RAytoun - Thanks for the idea. We added this new setting in the [v1.3 release](https://github.com/osmlab/applepaintstyles/releases/tag/v1.3) which is now live!

We also broke out the building validation settings into their own group for easier access. To enable this setting right-click on the paint style name > "Style settings" > "Building Validation Settings" > "Highlight nodes shared by buildings" 

<img width="589" alt="Screen Shot 2021-01-14 at 9 52 30 AM" src="https://user-images.githubusercontent.com/20782296/104630302-7927f900-564f-11eb-9c0a-4829eac6063c.png">

Buildings which share nodes will now flag: 

<img width="311" alt="Screen Shot 2021-01-14 at 10 04 40 AM" src="https://user-images.githubusercontent.com/20782296/104630723-00756c80-5650-11eb-80f0-c60862688f18.png">
