### ISSUE TITLE
Natural/landuse sharing a node with highway

### ISSUE THREAD

**Issue by RAytoun** [osmlab/applepaintstyles#15]
Is it possible to highlight with a triangle where a natural=* (such as natural=wood) or landuse=* (such as landuse=residential) shares a node with a highway

![Area shares node with highway](https://user-images.githubusercontent.com/10500102/96311664-e3ee7780-1001-11eb-9288-562669ddbcbe.jpg)

**Comment by westlakej** [comment]
Hey @RAytoun - Yes it is possible to do this and a great idea! We added this highlighting as a new setting in the [v1.3 release](https://github.com/osmlab/applepaintstyles/releases/tag/v1.3). 

To enable this setting right-click on the paint style name > "Style settings" > "Validation Settings" > "Landuse/Natural snapped to road"

<img width="595" alt="Screen Shot 2021-01-14 at 9 53 24 AM" src="https://user-images.githubusercontent.com/20782296/104631506-31a26c80-5651-11eb-873c-18dfc2c6eca6.png">

With this setting enabled, all intersections between landuse or natural areas and highways will flag if they share a node: 

<img width="424" alt="Screen Shot 2021-01-14 at 10 16 20 AM" src="https://user-images.githubusercontent.com/20782296/104631923-cc02b000-5651-11eb-835c-9653c3ff6ab4.png">

Happy Mapping!
