### ISSUE TITLE
Update overlapping building message if overlap no longer exists

### ISSUE THREAD

**Issue by wireguy** [osmlab/applepaintstyles#16]
If two buildings overlap, the overlap message shows in both buildings.   If I delete one of the buildings there is no long any overlap.   It would be nice if the other buildings message goes away.  

I could just ignore the message, since it no longer applies, but on a task that has lots of overlaps it's hard to keep track.
To remove the message, I need to perform an action on the building.    I usually just square it, and the message goes away.

If getting rid of the message is difficult, it would be nice if I could just 'touch' the building by clicking on  it, and having the message go away.

Here is an image of two buildings that overlap:
![image](https://user-images.githubusercontent.com/47227325/96348674-821d2480-1078-11eb-9040-36658ba2bf44.png)

And after I delete one of the buildings, the message is still in the other building:
![image](https://user-images.githubusercontent.com/47227325/96348714-c6102980-1078-11eb-8d75-1dc3ba68bca0.png)

**Comment by ddkpisme** [comment]
Hi @wireguy thanks for your feedback! I believe this is more in line with a JOSM request. We've noticed in the past that zooming in and out / refreshing the style will cause JOSM to re-render and properly replace the message you see here. I'm not sure we have a lot of control over this at the moment as far as our paint style goes, but if this changes we'll definitely revisit this.
