### ISSUE TITLE
Semi-detached houses are suspicious.

### ISSUE THREAD

**Issue by bolli24** [osmlab/applepaintstyles#17]
Both commonly used tags for semi-detached houses building=semi and building=semidetached_house are marked as suspicous building values.

**Comment by westlakej** [comment]
Hi @bolli24, thanks for reporting this! We will take a look and circle back with a solution.

**Comment by westlakej** [comment]
We added exceptions to these tags in the [v1.3 release](https://github.com/osmlab/applepaintstyles/releases/tag/v1.3). 

Building=semi and building=semidetached_house will no longer flag as suspicious. 

Thanks and Happy Mapping!

**Comment by bolli24** [comment]
Thank you for this great addition.
