### ISSUE TITLE
 building=fire_station

### ISSUE THREAD

**Issue by mdelatorre** [osmlab/applepaintstyles#9]
I really like using Apple Paint Style in my OSM mapping. But I found an issue with the validation of 
the tag building=fire_station as is validated as Suspicious Building Value. 

An example of the use of this tag is in: https://www.openstreetmap.org/way/265996274

![image](https://user-images.githubusercontent.com/1688146/90695000-3815ef00-e23f-11ea-9af9-a3d5d391e7e2.png)

mdelatorre

**Comment by ddkpisme** [comment]
Hi @mdelatorre - Glad you enjoy the style and thanks for pointing this out! We'll get this fixed in our next release.

**Comment by westlakej** [comment]
Hi @mdelatorre - This issue was resolved in https://github.com/osmlab/applepaintstyles/pull/12 and included in [v1.2.4](https://github.com/osmlab/applepaintstyles/releases/tag/v1.2.4). Thanks for reporting this. Happy mapping!
